# Generated by Django 4.2.2 on 2023-06-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
