# Generated by Django 4.2.2 on 2023-06-23 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuarios_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nome',
            new_name='NOME',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='senha',
            new_name='SENHA',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='sobrenome',
            new_name='SORENOME',
        ),
    ]
