"""Ajuste_CPF_tabela_Atleta

Revision ID: 178e0a26f9f2
Revises: ec2b80b7fec7
Create Date: 2024-05-20 15:51:28.169757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178e0a26f9f2'
down_revision: Union[str, None] = 'ec2b80b7fec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
