"""Ajuste_Schema_tabela_Atleta

Revision ID: 398b5f73c921
Revises: 178e0a26f9f2
Create Date: 2024-05-20 16:21:42.458741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398b5f73c921'
down_revision: Union[str, None] = '178e0a26f9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
