"""nova_migracao

Revision ID: 515bcc1a857b
Revises: b411bb794f55
Create Date: 2024-05-19 12:08:22.729984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515bcc1a857b'
down_revision: Union[str, None] = 'b411bb794f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atletas', 'nome',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=90),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atletas', 'nome',
               existing_type=sa.String(length=90),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
