"""criar_tabelas_iniciais

Revision ID: ec2b80b7fec7
Revises: 8fda2515a735
Create Date: 2024-05-19 21:16:26.754899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2b80b7fec7'
down_revision: Union[str, None] = '8fda2515a735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
