version: "3.9"
services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: "00000"
      POSTGRES_USER: postgres
      POSTGRES_DB: workout
    ports:
      - "5432:5432"
